[package]
name = "futbladaj"
version = "0.1.0"
authors = ["Daniel José Domingos Serrano <danieljdserrano@gmail.com>"]
edition = "2018"

[dependencies]
clap = { git = "https://github.com/clap-rs/clap", branch = "master", features = ["yaml"] }
ureq = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
