#[derive(Debug)]
pub struct Params<'a> {
    pub pitch: &'a str,
    pub day: i32,
    pub month: i32,
    pub year: i32,
    pub start_hour: i32,
    pub start_minute: i32,
    pub end_hour: i32,
    pub end_minute: i32,
    pub user_type: &'a str,
    pub username: &'a str,
    pub email: &'a str,
    pub phone: &'a str,
    pub bday_day: i32,
    pub bday_month: i32,
    pub bday_year: i32,
    pub fiscal_number: &'a str,
    pub address: &'a str,
    pub postcode: &'a str,
    pub location: &'a str,
}

impl<'a> Params<'a> {
    pub fn new(
        username: &'a str,
        email: &'a str,
        fiscal_number: &'a str,
        phone: &'a str,
        address: &'a str,
        postcode: &'a str,
        location: &'a str,
        day: i32,
        month: i32,
        year: i32,
        start_hour: i32,
        start_minute: i32,
        end_hour: i32,
        end_minute: i32,
    ) -> Self {
        Params {
            username,
            email,
            fiscal_number,
            phone,
            address,
            postcode,
            location,
            day,
            month,
            year,
            start_hour,
            start_minute,
            end_hour,
            end_minute,
            pitch: "123",
            user_type: "outros",
            bday_day: 1,
            bday_month: 1,
            bday_year: 1990,
        }
    }
}
